# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='author',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='date',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='author',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='date',
        ),
        migrations.AlterField(
            model_name='poll',
            name='ballots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='result',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='voice',
            name='opinion',
            field=models.TextField(),
        ),
    ]
