# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0002_auto_20160320_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='sentiment',
            field=models.CharField(default='Unsure', max_length=20),
        ),
    ]
