# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0004_auto_20160322_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='author',
        ),
    ]
