# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0005_remove_poll_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 22, 13, 12, 32, 2291)),
        ),
    ]
