# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0008_auto_20160322_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 13, 26, 46, 188865)),
        ),
    ]
