# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0010_auto_20160323_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 13, 46, 28, 255391)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='sentiment',
            field=models.CharField(default='Not enough votes!', max_length=20),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 13, 46, 28, 255391)),
        ),
    ]
