# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 21:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0011_auto_20160323_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 16, 36, 59, 799357)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='sentiment',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 16, 36, 59, 799357)),
        ),
    ]
