# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0012_auto_20160323_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 24, 9, 34, 52, 724651)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 24, 9, 34, 52, 724651)),
        ),
    ]
