# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 15:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0014_auto_20160324_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 24, 10, 4, 32, 906471)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 24, 10, 4, 32, 913982)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
