# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0015_auto_20160324_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 13, 7, 12, 519025)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 13, 7, 12, 519025)),
        ),
    ]
