# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0017_auto_20160326_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='question',
            new_name='poll_question',
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 13, 13, 31, 173214)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 13, 13, 31, 173214)),
        ),
    ]
