# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0018_auto_20160326_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='poll_question',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 13, 17, 46, 430740)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 13, 17, 46, 430740)),
        ),
    ]
