# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 19:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pll', '0020_auto_20160326_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpDownVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='upvoter',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='voice',
        ),
        migrations.RenameField(
            model_name='voice',
            old_name='upvotes',
            new_name='updown_votes',
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 14, 24, 28, 750790)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 26, 14, 24, 28, 752291)),
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
        migrations.AddField(
            model_name='updownvote',
            name='voice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pll.Voice'),
        ),
        migrations.AddField(
            model_name='updownvote',
            name='voter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
