# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 13:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0021_auto_20160326_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='user_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 8, 36, 15, 41308)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 8, 36, 15, 41308)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ballot',
            field=models.IntegerField(choices=[(-2, 'Strongly disagree'), (-1, 'Disagree'), (0, 'Unsure'), (1, 'Agree'), (2, 'Strongly Agree')]),
        ),
    ]
