# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0022_auto_20160327_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice',
            old_name='user_vote',
            new_name='uservote',
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 8, 42, 8, 253697)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 27, 8, 42, 8, 253697)),
        ),
    ]
