# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0028_auto_20160329_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='poll',
            name='tally',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 2, 12, 59, 7, 412543)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='result',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='poll',
            name='tag',
            field=models.CharField(choices=[('Community Development', 'Community Development'), ('Education', 'Education'), ('Sustainability', 'Sustainability'), ('Facilities', 'Facilities'), ('Health & Human Services', 'Health & Human Services'), ('Historic Preservation', 'Historic Preservation'), ('Parks & Rec', 'Parks & Rec'), ('Public Safety', 'Public Safety'), ('Sanitation', 'Sanitation'), ('Transportation', 'Transportation')], default='no tag', max_length=30),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 2, 12, 59, 7, 413544)),
        ),
    ]
