# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0029_auto_20160402_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='tally',
            new_name='avg_vote',
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 2, 13, 5, 16, 63189)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 2, 13, 5, 16, 64689)),
        ),
    ]
