# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0033_auto_20160402_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 15, 27, 17, 820264)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='poll',
            name='tag',
            field=models.CharField(choices=[('admin', 'Administration & Finance'), ('buildings', 'Buildings'), ('community', 'Community Development'), ('education', 'Education'), ('events', 'Events'), ('sustainability', 'Environment and Sustainability'), ('health', 'Health & Human Services'), ('parks', 'Parks & Rec'), ('safety', 'Public Safety'), ('sanitation', 'Sanitation'), ('transportation', 'Transportation')], default='no tag', max_length=30),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 15, 27, 17, 825767)),
        ),
    ]
