# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0034_auto_20160411_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 14, 41, 55, 920672)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='tag',
            field=models.CharField(choices=[('admin', 'Administration & Finance'), ('buildings', 'Buildings'), ('community', 'Community Development'), ('education', 'Education'), ('events', 'Events'), ('sustainability', 'Environment and Sustainability'), ('health', 'Health & Human Services'), ('parks', 'Parks & Rec'), ('safety', 'Public Safety'), ('sanitation', 'Sanitation'), ('transportation', 'Transportation'), ('other', 'Other')], default='no tag', max_length=30),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 14, 41, 55, 920672)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ballot',
            field=models.IntegerField(choices=[(-2, 'Very Negative'), (-1, 'Negative'), (0, 'Neutral'), (1, 'Positive'), (2, 'Very Positive')]),
        ),
    ]
