# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 20:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0035_auto_20160413_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='constituent',
            name='neighborhood',
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 29, 15, 45, 37, 994227)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(default='Create a Poll', max_length=150),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 29, 15, 45, 38, 1736)),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ballot',
            field=models.IntegerField(choices=[(2, 'Very Positive'), (1, 'Positive'), (0, 'Neutral'), (-1, 'Negative'), (-2, 'Very Negative')]),
        ),
    ]
