# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 06:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0040_auto_20160429_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 30, 1, 8, 31, 934117)),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 30, 1, 8, 31, 943123)),
        ),
    ]
