# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 02:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pll', '0043_auto_20160514_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='glyph',
        ),
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 14, 21, 46, 56, 168937)),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 14, 21, 46, 56, 168937)),
        ),
    ]
