# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstituentEval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='no tag', max_length=30)),
                ('result', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sentiment', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
