# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='flag',
            name='tally',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='flag',
            name='result',
            field=models.CharField(default='', max_length=30),
        ),
    ]
