# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flg', '0002_auto_20160402_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flag',
            old_name='tally',
            new_name='avg_vote',
        ),
    ]
