# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flg', '0003_auto_20160402_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='sentiment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
