# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flg', '0004_flag_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='tag',
            field=models.CharField(choices=[('admin', 'Administration & Finance'), ('buildings', 'Buildings'), ('community', 'Community Development'), ('education', 'Education'), ('events', 'Events'), ('sustainability', 'Environment and Sustainability'), ('health', 'Health & Human Services'), ('parks', 'Parks & Rec'), ('safety', 'Public Safety'), ('sanitation', 'Sanitation'), ('transportation', 'Transportation'), ('other', 'Other')], default='no tag', max_length=30),
        ),
    ]
